\c my_spectrum;

INSERT INTO toys (name, description, price, category, type, is_available, image) VALUES 
('Wighted Banket', 'Weighted blankets have been shown to increase relaxation, while decreasing stress and anxiety due to deep touch pressure.  It is supposed to activate a sensory response that has a similar calming effect of a big hug.', 30, 'touch', 'Hypo-Sensitive', true, 'https://m.media-amazon.com/images/I/71WSL5sN5PL._AC_SL1500_.jpg'),
('Buddha Board', 'Kids will love writing words or painting pictures on this simple board that uses water as paint.  As the water evaporates, the canvas becomes a blank slate to start fresh again.', 20, 'sight', 'Hyper-Sensitive', true, 'https://m.media-amazon.com/images/I/718bIkwBVAL._AC_SL1500_.jpg'),
('Bubbler/Mini Lava Lamp Timer', 'This bubbler timer is great relaxation toy when emotions are high.  The slow progress of the oil droplets can be very soothing and calming for a child after a sensory meltdown or any time they need to unwind.', 15, 'sight', 'Hyper-Sensitive', true, 'https://m.media-amazon.com/images/I/71wcNJB20ZL._SL1500_.jpg'),
('Aquaglow Light-Up Jellyfish Hideaway', 'This jellyfish hideaway was in a calming room at a play place. It was such a hit with young kids.  In a low lit room, it provides a very calming visual and tactile experience.', 40, 'body awareness', 'Hyper-Sensitive',false, 'https://m.media-amazon.com/images/I/51bh96nChOL._AC_SL1024_.jpg'),
('Trampoline', 'This is a great gift for getting your child’s energy out, while providing vestibular input at the same time!', 60, 'balance', 'Hypo-Sensitive', false, 'https://m.media-amazon.com/images/I/81lUG+OzKHL._AC_SL1500_.jpg'),
('Kinetic Sand', 'This stuff is so cool, but hard to describe.  It feels like sand, but is easily molded without water.  It sticks together, but is not sticky or wet.  Kinetic sand is a really versatile toy that can provide a lot of benefits.  If your sensitive kids don’t like messy play or have tactile defensiveness, they will likely still be interested in trying this out.', 15, 'touch', 'Hypo-Sensitive', true, 'https://m.media-amazon.com/images/I/912YSUN0JLL._AC_SL1500_.jpg'),
('Gonge Top', 'This red top is inviting to sit in.  It allows you move all around and upside down, which encourages balance reactions, vestibular stimulation and spatial orientation.', 140, 'balance', 'Hypo-Sensitive', true, 'https://m.media-amazon.com/images/I/718LuYQ2BzL._AC_SL1500_.jpg'),
('Picasso Tiles', 'These magnetic building tiles let you craft 2D and 3D art in a unique way.  Great for encouraging creativity!', 50, 'sight', 'Hyper-Sensitive', true, 'https://m.media-amazon.com/images/I/91VrWJewlES._AC_SL1500_.jpg'),
('A-Z Alphabet Letters Numeral Foam Mat', 'Colorful Puzzle Kid Educational Toy', 55, 'touch, sight','Hyper-Sensitive', false, 'https://m.media-amazon.com/images/I/91T+psZNNAL._AC_SL1500_.jpg'),
('Farm Friends Sound & Go Musical Tractor', 'The farm animals can be placed on the ground and the tractor on a low table, the children squat down to get an animal and have to come to stand to place it in the tractor.', 30, 'sound', 'Hypo-Sensitive', false, 'https://m.media-amazon.com/images/I/71MDgvx7X2L._AC_SL1500_.jpg'),
('Wireless Headphones', 'A true game changer, these headphones padded ear cups offer comfort when kids get exposed by unwanted sounds. They are also Bluetooth ready and can be used with radios, video games, and other devices.', 35, 'sound', 'Hyper-Sensitive', true, 'https://m.media-amazon.com/images/I/617uzAU2LRL._AC_SL1000_.jpg'),
('Sit N Spin','This old-school toy allows kids to spin at their own pace, laugh, and play with their siblings in an activity they enjoy. Kids on the spectrum generally enjoy the sensation of spinning. Our son loves it!', 35, 'balance', 'Hypo-Sensitive', false, 'https://m.media-amazon.com/images/I/715hOh1hDHL._AC_SL1500_.jpg');

